import Head from 'next/head'
import styles from "../styles/home.module.css"
import Navbar from '../components/navigatorbar'

export default function about() {
    return (
        <div className={styles.container}>
            <Head>
                <title>kenryuS: About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.jpeg" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    About: <a href='https://github.com/kenryuS'>kenryuS</a>
                </h1>

                <p className={styles.description}>
                    About page of kenryuS.<br/><b style={{color: 'rgb(194, 199, 44)'}}>Warning: This website is under construction!</b>
                </p>
            </main>
        </div>
    );
}
