import Head from 'next/head'
import styles from "../styles/home.module.css"
import Navbar from '../components/navigatorbar'

export default function about() {
    return (
        <div className={styles.container}>
            <Head>
                <title>kenryuS: About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.jpeg" />
            </Head>

            <div className={styles.mainContent}>
                <h1 className={styles.title}>
                    About This Website:
                </h1>

                <p className={styles.description}>
                    This is <a href="https://github.com/kenryuS">kenryuS</a> website hosted by vercel. There is separate website for portfolio: <a href="https://kenryu-liveterm.vercel.app">https://kenryu-liveterm.vercel.app</a>
                </p>
            </div>
        </div>
    );
}
