import Head from 'next/head'
import styles from '../styles/home.module.css'
import FloatMenu from '../components/floatmenu'

export default function Home() {
  return (
    <div className={styles.container}>
        <Head>
            <title>kenryuS Website</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.jpeg" />
        </Head>

        <FloatMenu>
	    <div>
                <p>Test</p>
                <p>Test</p>
	    </div>
        </FloatMenu>

        <main className={styles.main}>
            <h1 className={styles.title}>
                Welcome to <a href='https://github.com/kenryuS'>kenryuS</a> website!
            </h1>

            <p className={styles.description}>
                This is the website of kenryuS.<br/><b style={{color: 'rgb(194, 199, 44)'}}>Warning: This website is under construction!</b>
            </p>
        </main>
    </div>
  )
}
